### ISSUE TITLE
BLU10 – Learning Notebook Appendix – A.2.3 – missing arguments in csr_matrix() and csc_matrix()

### ISSUE THREAD

**Issue by Juliana-R** [LDSSA/batch3-students#109]
**Learning unit**
BLU10

**Describe the issue**
In section A2.3, I believe some arguments are missing in the definition of the CSR sparse matrix:
`H_ = csr_matrix(data)`
with `data = np.array([1, 2, 1, 5, 2, 1])` defined on the preceding cell.
Same goes for the CSC matrix defined on the same section.

**Comment by UrbanoFonseca** [comment]
You are right indeed. The matrices should be initiated with something like:
```
H_ = csr_matrix((data, (row, col)))
H_
```

**Comment by UrbanoFonseca** [comment]
This issue should be closed with the following commit: https://github.com/LDSSA/batch3-students/commit/82ed23603911cb963a62fc9bb4d8008f3965ed90.
Please review @Juliana-R :)
