### ISSUE TITLE
BLU10 LN 2/3 - Wrong value for CSR 

### ISSUE THREAD

**Issue by snovaisg** [LDSSA/batch3-students#110]
**Learning unit**
BLU10 Learning Notebook 2

**Describe the bug**
In section 3.1.2 "compressed sparse rows" are introduced and an example matrix is given where it is written that its indptr =  [0, 2, 2, 4]. But i believe it should be [0, 2, 2, 3]. This subject took a while to understand because that last value seems wrong, it makes more sense it if is 3 so can someone please check that and correct so that next batch students won't also spend time figuring it out?

**Screenshots**

![Screenshot 2019-11-05 at 17 15 25](https://user-images.githubusercontent.com/24900912/68229926-06090880-fff0-11e9-93c1-4471c8ee61ec.png)

**Comment by UrbanoFonseca** [comment]
Thank you for raising this issue! 

You are right, the indptr array should be [0, 2, 2, 3]
![image](https://user-images.githubusercontent.com/25173321/69016184-15933480-0994-11ea-9dd5-4a9f004cc091.png)

**Comment by UrbanoFonseca** [comment]
This issue should be closed with commit https://github.com/LDSSA/batch3-students/commit/82ed23603911cb963a62fc9bb4d8008f3965ed90.
Please review @snovaisg :)
