### ISSUE TITLE
BLU10 Exercise Notebook Q2 - repeated question

### ISSUE THREAD

**Issue by snovaisg** [LDSSA/batch3-students#111]
**Describe the bug**
In Q2, the second task in this question asks us to complete the function _get_sparsity_representation_savings_, however, the hash in the assert cell below  is identical to the one from the first question of this Exercise. I believe the expected answer for the second question is supposed to be different from what the first question is asking.

Also, the question should be asking us to round our result up to a certain decimal so that the assert doesn't go wrong for different people

**Screenshots**
![Screenshot 2019-11-05 at 18 22 47](https://user-images.githubusercontent.com/24900912/68234533-52a51180-fff9-11e9-8b11-1d89fde90213.png)

**Comment by UrbanoFonseca** [comment]
This issue should be closed with commit https://github.com/LDSSA/batch3-students/commit/82ed23603911cb963a62fc9bb4d8008f3965ed90.
Please review @snovaisg :)
