### ISSUE TITLE
BLU11 Exercise Notebook Q4.3 - Difficult troubleshooting

### ISSUE THREAD

**Issue by rjna** [LDSSA/batch3-students#115]
**Learning unit**
BLU 11
**Describe the bug**
In BLU11, the values of the dataframe in 4.1.3 are not tested. This has repercussions in Q4.3 that are difficult to troubleshoot. An additional assert should be done in 4.1.3 so that only matrices with the correct values pass the assert.

**To Reproduce**
Verify that any matrix with the correct shape and index will pass the assert in 4.1.3.

**Expected behavior**
Only matrices with the correct values should pass the assert.

**Screenshots**
Not applicable.

**Additional context**
Nothing to add.

**Comment by dominguezmaria** [comment]
See the answer for this other [issue](https://github.com/LDSSA/batch3-students/issues/117).
