### ISSUE TITLE
BLU11 Exercise Notebook Q4.3 and Q4.1.3 - Assert accepting an incorrect answer

### ISSUE THREAD

**Issue by rjna** [LDSSA/batch3-students#117]
**Learning unit**
BLU11 Exercise Notebook Q4.3 and Q4.1.3

**Describe the bug**
In Q4.1.3, we're told to create a feature "year". This feature should be created by extracting the year between parenthesis of the "title" feature.
The assert in Q4.1.3 then does not test the values of the preprocessed_movies, so if the df has the correct index, it passes the assert. This situation is already described in https://github.com/LDSSA/batch3-students/issues/115.
However, the assert on Q4.3 depends on the values of the preprocessed_movies df, so the way that you create the feature "year" will determine if you pass the assert (or not).
Right now, I'm passing the assert with the following line of code:
preprocessed_movies["year"] = preprocessed_movies["title"].str.split().apply(lambda x: x[-1]).str.replace("(\(|\))", "")

However, this line of code does not deal with the edge cases, e.g., when the "title" feature has strings without years in parenthesis. E.g.: 
![image](https://user-images.githubusercontent.com/25709252/68865081-199c2980-06ea-11ea-914e-82a0a85353fd.png)

So, it is indeed a not totally correct way to solve the problem, but it's the way that you should solve in order to pass the assert. Given this, there are two possible options: 
i) Everything stays as it is, but the exercise should state that we do not need to worry about this edge cases
ii) The assert should only pass with a solution that deals with these edge cases (e.g., if there isn't any number between parenthesis, the feature should have an empty string)

**To Reproduce**
Confirm that the assert of Q4.3 only passes if you create the feature "year" in this way.

**Expected behavior**
One of two possible behaviors:
i) Everything stays as it is, but the exercise should state that we do not need to worry about this edge cases
ii) The assert should only pass with a solution that deals with these edge cases (e.g., if there isn't any number between parenthesis, the feature should have an empty string)

**Screenshots**
Added before.

**Additional context**
No additional context.

**Comment by dominguezmaria** [comment]
@rjna thank you for opening the issue!
In fact, the current accepted solution doesn't handle the edge cases that you were describing.

However, in order to avoid changing the asserts (which would require students re-submitting), and not to give too much attention to a non RecSys related problem, we'll go with your first suggested solution.
So, we're not going to change the assert, and instead share with all the students that they should use the following piece of code on question Q4.1.3:

```
preprocessed_movies["year"] = preprocessed_movies["title"].str.split().apply(lambda x: x[-1]).str.replace("((|))", "")
```

We'll change the description on the Exercise Notebook ASAP!
