### ISSUE TITLE
SLU02 Exercise notebook - Exercise9 function missing

### ISSUE THREAD

**Issue by snovaisg** [LDSSA/batch3-students#29]
**Learning unit**
SLU02 - Exercise Notebook

**Describe the bug**
The function definition exercise_9 is missing

**To Reproduce**
Go to the section *Exercise 9* of the notebook

**Expected behavior**
It should be there.

**Screenshots**
![Screenshot 2019-07-06 at 10 48 38](https://user-images.githubusercontent.com/24900912/60754687-b59b8300-9fdc-11e9-95e3-322dc02643ea.png)

**Comment by snovaisg** [comment]
Related to this issue:

Either the asserts have a mistake or the question. 

For example, in the columns it asks for restaurant name,neighbourhood , average_cost_for_two and the booking availablily

and the assert is assert len(df_test.columns) == 5

I think more asserts might be wrong but this section of exercise 9 should be reviewed entirely.

**Comment by aespedrosa** [comment]
Problem identified. A new commit will be done with the fix.

**Comment by gaborsomogyi** [comment]
fixed: updated description and added code explanation
