### ISSUE TITLE
SLU09 exercise 5.2 - can't get the right answer on  L (paraphrased from a student DM)

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/batch3-students#54]
Question: 
> When calculating L on 5.2, the answer is a numeric value, but the grader does not accept it. 

Suggestion: 
> Read the arguments of the function carefully. Betas is not of the same shape as y, because the first element is the intercept. You may not want the first element in this calculation.

**Comment by PedroGFonseca** [comment]
@hcastilho once answered, should we close it? (this one is a bit meta because it was a DM in slack, but is probably useful to other students)

**Comment by hcastilho** [comment]
Yes we should, otherwise it will become impossible for the instructor to distinguish what has been done.
But I've made the mistake of only going through the open issues.

**Comment by cmaroti** [comment]
I think @PedroGFonseca's answer is good, can we close this?

**Comment by hcastilho** [comment]
Closing
