### ISSUE TITLE
SLU16 - Learning Curve min_train_set_size expecting an exact value

### ISSUE THREAD

**Issue by pralmeida** [LDSSA/batch3-students#55]
**Learning unit**
SLU16 - Data Sufficiency and Selection

**Describe the issue**
In the last exercise, the assert for the `min_train_set_size `is expecting an exact value, and that exact value is none of the ones in `train_sizes`. 

The assert should test for a range of values or for one of the values in `train_sizes`.

**Comment by hershaw** [comment]
This is indeed my bad. Will work on this ASAP.
