### ISSUE TITLE
SLU16 feature importance exercise should specify which tree based classifier to use

### ISSUE THREAD

**Issue by cmaroti** [LDSSA/batch3-students#56]
**Learning unit**
SLU16 - data sufficiency and selection

**Describe the bug**
The exercise "Find the rest of the useless features" says to use a tree based classifier, but the tests only work with random forests. There was a student using decision trees and his code would not pass the tests. The instructions should be updated to specify random forests, or the tests should be made to work with any tree based classifier.

**Comment by cmaroti** [comment]
@hershaw

**Comment by hershaw** [comment]
This one has already been fixed and added actually. The new version looks like this:

![image](https://user-images.githubusercontent.com/424192/61185590-123d1480-a653-11e9-8fee-014ffa367aba.png)

May I close this?

**Comment by cmaroti** [comment]
Oops sorry for the duplicate! I'll close it

**Comment by hershaw** [comment]
So there were still some people complaining about it because some confusing language was still in there. Turns out you were correct in opening it after all @cmaroti!
