### ISSUE TITLE
SLU16 - Learning Curve

### ISSUE THREAD

**Issue by n-loureiro** [LDSSA/batch3-students#57]
### sklearn version installed in the environment seems to be different changed from the evaluators' one.

sklearn version in environment is 0.21.2, which outputs a warning if no cv is selected in learning_curve function. Default for this version is cv=3 which does not pass the asserts. Changing to cv= 5 solves that problem.

---

Later in the exercise, the plot for the learning curves seem to indicate that the value for min_train_set_size should be around 430. However, the value expected in the asserts is much lower than that.

This can again suggest that the versions of sklearn used by the evaluators were different from the ones that we have installed in the environment (....or that I'm doing something wrong ;) ).

**Comment by hcastilho** [comment]
The grader also creates an environment using the `environment.yml` so it's improbable that it has a different version.
Let's se what @hershaw has to say and we'll revisit that hypothesis later.

**Comment by hershaw** [comment]
I'm not hearing about anyone else having this issue. Did you get it worked out @n-loureiro?

**Comment by Juliana-R** [comment]
Closing this issue as it is now over 1.5 years old. Feel free to reopen it.
