### ISSUE TITLE
SLU18 Exercise notebook: assert statement in Exercise 1

### ISSUE THREAD

**Issue by jnpicao** [LDSSA/batch3-students#71]
**Learning unit**
SLU18 - exercise notebook (exercise 1, first step)

**Describe the issue**
Could you please confirm the correspondence between the following assert statement:

`assert all(num in grid["C"] for num in [0.5  , 0.875, 1.25 , 1.625, 2. ])`

and the question:

> (1.1) Create a hyperparameter search space with the following specifications: Inverse of regularization strength 'C' between 0.5 and 2, with increments of 0.5; kernel: "linear" and "rbf")

**Comment by Luisfandrade** [comment]
There is indeed a typo in the question. This has been corrected in PR https://github.com/LDSSA/batch3-instructors/pull/81 and is waiting approval from the QA team to be merged
