### ISSUE TITLE
SLU000 Examples notebook - FileNotFoundError

### ISSUE THREAD

**Issue by snovaisg** [LDSSA/batch3-students#8]
**SLU000**

**Describe the bug**
From the point the notebook tries to read the file "data/iris.csv", no code cells work after that because the file doesn't exist and they depend on it.

**To Reproduce**
Just run the notebook from the code cell which has the line "iris = pd.read_csv('data/iris.csv')"

**Expected behavior**
It should be able to read the file

**Screenshots**
![Screenshot 2019-07-01 at 15 19 19](https://user-images.githubusercontent.com/24900912/60443670-a058da00-9c13-11e9-8bec-1e44a99e6731.png)

**Comment by hershaw** [comment]
Good catch, thanks for that! We've got a fix incoming but it's not a super-high priority until after the bootcamp ends.

**Comment by hershaw** [comment]
We've got a PR open for this one that's ready for QA. Solution should be inbound shortly!
